import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const files = {
	backlog: resolve(repoRoot, "docs/BACKLOG.md"),
	changelog: resolve(repoRoot, "docs/CHANGELOG.md"),
	githubSync: resolve(repoRoot, "docs/GITHUB_SYNC.md"),
	githubLiveIssueSync: resolve(
		repoRoot,
		"scripts/github-live-issue-sync.test.mjs",
	),
};

function readRequiredFile(path) {
	assert.ok(existsSync(path), `missing required file: ${path}`);

	const content = readFileSync(path, "utf8");
	assert.ok(content.trim().length > 0, `empty required file: ${path}`);
	return content;
}

function uniqueLabelsFromBacklog(backlog) {
	return [
		...new Set(
			backlog
				.split("\n")
				.filter((line) => line.startsWith("Labels:"))
				.flatMap((line) =>
					Array.from(line.matchAll(/`([a-z][a-z0-9:-]+)`/g), ([, label]) =>
						label.trim(),
					),
				),
		),
	].sort();
}

function expectContains(content, needle, label = needle) {
	assert.ok(
		content.includes(needle),
		`expected GitHub sync to include ${label}`,
	);
}

test("GitHub sync runbook mirrors backlog taxonomy and project-scope blocker", () => {
	const backlog = readRequiredFile(files.backlog);
	const changelog = readRequiredFile(files.changelog);
	const githubSync = readRequiredFile(files.githubSync);
	const githubLiveIssueSync = readRequiredFile(files.githubLiveIssueSync);
	const labels = uniqueLabelsFromBacklog(backlog);

	assert.ok(labels.length >= 20, "expected backlog taxonomy labels");

	for (const label of labels) {
		expectContains(githubSync, `\`${label}\``, `label ${label}`);
	}

	for (const required of [
		"gh auth refresh --hostname github.com -s project,read:project",
		"Manual Project auth recovery cases",
		"Listing only: `gh auth refresh --hostname github.com -s read:project`",
		"Create or update: `gh auth refresh --hostname github.com -s project,read:project`",
		"Auth refresh only proves the token has scopes; it does not prove the Project board exists or is current.",
		"GitHub Project recovery is complete for the current open issue bridge",
		"https://github.com/users/HumanKaylee/projects/1",
		"Synced open bridge issues:",
		"Tracked pull requests: `#6`",
		"Project fields: default `Status` plus `Phase`, `Priority`, `Type`, `Area`,",
		"Skip reasons: none; every currently open issue in the live bridge has a",
		"Repo issue bodies remain the source of truth",
		"not as launch-readiness evidence",
		"Live Project permission recheck as of 2026-05-25T13:23:35-04:00",
		"Project #1 permission recheck passed after HumanKaylee's permission update.",
		"no auth refresh is required for the current local token",
		"4bc6674586fa66c76ba673006cdf1192d6230774",
		"PR #6 Project tracking recheck",
		"gh project item-add 1 --owner HumanKaylee --url https://github.com/HumanKaylee/humankaylee-portfolio/pull/6 --format json",
		"PR #6 is tracked on Project #1",
		"`projectItems` reports `HumanKaylee Portfolio` with status `Todo`",
		"Latest PR #6 Project write recheck as of 2026-05-25T14:18:48-04:00",
		"PR #6 remains tracked on Project #1 with status `In Progress`",
		"Project #1 write",
		"access is healthy",
		"0094a2b99470d3b7dbbabb2630b2c309a217de2b",
		"26413621250",
		"77753216749",
		"77753216723",
		"`viewerCanUpdate:true`",
		"Latest GitHub Project permission recheck as of 2026-05-25T15:00:35-04:00",
		"Project #1 still lists/views successfully",
		"PR #6 remains tracked on Project #1 with status `In Progress` at head",
		"f318798e2d090892fb53ebb1eb0b1817cbb7bc85",
		"26415093835",
		"77757735460",
		"77757735457",
		"Missing scopes: none observed",
		"GH_PROMPT_DISABLED=1 gh project field-list 1 --owner HumanKaylee --format json",
		"GH_PROMPT_DISABLED=1 gh project item-list 1 --owner HumanKaylee --limit 200 --format json",
		"GH_PROMPT_DISABLED=1 gh api graphql",
		"HK_VERIFY_GITHUB_LIVE=1 node --test scripts/github-live-issue-sync.test.mjs",
		"Embedded Project recovery snapshot as of 2026-05-25",
		"Project recovery snapshots are point-in-time evidence; do not rewrite this section only to chase the current PR head.",
		"gh auth status -h github.com",
		"Snapshot token scopes:",
		"`project`",
		"The embedded read-only Project check succeeded and returned Project #1 with 15 synced",
		'"items":{"totalCount":15}',
		"GitHub Project recovery is complete",
		"Project #1 provides the triage/status view",
		"If `GH_PROMPT_DISABLED=1 gh project list --owner HumanKaylee --format json`",
		"GH_PROMPT_DISABLED=1 gh project list --owner HumanKaylee --format json",
		"GH_PROMPT_DISABLED=1 gh project list --owner HumanKaylee --format json | jq -r '.projects[] | select(.title == \"HumanKaylee Portfolio\") | [.number, .title, .url] | @tsv'",
		"Use `GH_PROMPT_DISABLED=1` for Project discovery checks",
		"Do not run `gh auth refresh` from unattended automation.",
		"missing required scopes [project read:project]",
		"missing required scopes [read:project]",
		"Keep fields for phase, priority, type, area, agent size, status, and blocker",
		"gh project item-add <project-number> --owner HumanKaylee --url https://github.com/HumanKaylee/humankaylee-portfolio/issues/<issue-number>",
		"Do not mark a future Project sync current until every open issue in the live",
		"gh label create",
		"gh issue edit",
		"gh issue create",
		"Live issue bridge snapshot as of 2026-05-24",
		"Legacy `phase-0` through `phase-5` labels remain on the coarse issues",
		"Granular Issue Sync",
		"#7",
		"B-001: Confirm launch positioning and audience order",
		"#8",
		"B-002: Create public-safety and redaction checklist",
		"#9",
		"B-003: Inventory case-study candidates",
		"#10",
		'B-004: Define "The Systems Atelier" design brief',
		"#11",
		"B-005: Resolve launch blockers register",
		"Phase 1 backlog issues now live as the next granular sync layer",
		"#12",
		"B-006: Scaffold Astro TypeScript frontend",
		"#13",
		"B-007: Configure content collections",
		"#14",
		"B-008: Build base layout and semantic shell",
		"#15",
		"B-009: Establish CSS token system",
		"#16",
		"B-010: Add baseline CI checks",
		"#17",
		"B-011: Add frontend test harness",
		"#18",
		"B-012: Add Playwright smoke-test harness",
		"Phase 2 backlog issues now live as the next granular sync layer",
		"#19",
		"B-013: Write launch home-page content package",
		"#20",
		"B-014: Draft case study: CLI fleet synchronization and MCP rollout",
		"#21",
		"B-015: Draft case study: remote workstation recovery and operational debugging",
		"#22",
		"B-016: Draft case study: HumanKaylee portfolio build",
		"#23",
		"B-017: Draft case study: creative web demo",
		"#24",
		"B-018: Evaluate Kalshi or analytics tooling publication safety",
		"#25",
		"B-019: Evaluate YouTube AI video pipeline publication safety",
		"#26",
		"B-020: Build resume content source",
		"#27",
		"B-021: Create notes/build-log starter content",
		"Phase 3 backlog issues now live as the next granular sync layer",
		"#28",
		"B-022: Implement static home page",
		"#29",
		"B-023: Implement project index and category filters",
		"#30",
		"B-024: Implement case-study routes",
		"#31",
		"B-025: Implement resume HTML page and PDF link",
		"#32",
		"B-026: Implement contact page or section with fallback",
		"#33",
		"B-027: Implement notes/build-log pages and RSS",
		"#34",
		"B-028: Add SEO metadata and structured data",
		"#35",
		"B-029: Add sitemap and robots.txt",
		"#36",
		"B-030: Add static project metadata fallback",
		"Phase 4 backlog issues now live as the next granular sync layer",
		"#37",
		"B-031: Implement art-directed page surfaces",
		"#38",
		"B-032: Implement static hero poster and fallback",
		"#39",
		"B-033: Implement accessible project atlas fallback",
		"#40",
		"B-034: Implement desktop project constellation",
		"#41",
		"B-035: Add purposeful scroll and reveal motion",
		"#42",
		"B-036: Add view transitions or route continuity",
		"#43",
		"B-037: Add visual regression snapshots",
		"Phase 4 issue sync status: complete",
		"Phase 5 backlog issues now live as the next granular sync layer",
		"#44",
		"B-038: Scaffold Rust Axum API service",
		"#45",
		"B-039: Implement `GET /api/health`",
		"#46",
		"B-040: Implement cached `GET /api/projects/live`",
		"#47",
		"B-041: Implement contact endpoint validation",
		"#48",
		"B-042: Add contact rate limiting and abuse controls",
		"#49",
		"B-043: Add contact delivery or storage adapter",
		"#50",
		"B-044: Implement optional privacy-safe events endpoint",
		"#51",
		"B-045: Configure backend CORS and security middleware",
		"#52",
		"B-046: Add backend Dockerfile and Shuttle deploy path",
		"#53",
		"B-047: Integrate frontend with API fallbacks",
		"Phase 5 issue sync status: complete",
		"Phase 6 backlog issues now live as the next granular sync layer",
		"#54",
		"B-048: Add accessibility audit pass",
		"#55",
		"B-049: Add reduced-motion and no-WebGL QA pass",
		"#56",
		"B-050: Add Lighthouse production-like checks",
		"#57",
		"B-051: Add bundle analysis and performance budgets",
		"#58",
		"B-052: Add Playwright journey smoke tests",
		"#59",
		"B-053: Add security headers and dependency audit",
		"#60",
		"B-054: Add privacy documentation",
		"#61",
		"B-055: Add cross-browser and responsive QA pass",
		"#62",
		"B-056: Add API outage resilience test",
		"Phase 6 issue sync status: complete",
		"Phase 7 backlog issues now live as the next granular sync layer",
		"#63",
		"B-057: Configure Cloudflare Pages frontend deployment",
		"#64",
		"B-058: Deploy Rust API to selected host",
		"#65",
		"B-059: Configure production domain and canonical URLs",
		"#66",
		"B-060: Write local development and deployment README",
		"#67",
		"B-061: Write content update and redaction runbook",
		"#68",
		"B-062: Write rollback and incident runbook",
		"#69",
		"B-063: Complete launch checklist",
		"Phase 7 issue sync status: complete",
		"GitHub issue mirror evidence only",
		"Project #1 sync is tracked",
		"neither source is production launch or launch-readiness",
		"Project board maintenance steps",
		"Phase 8 backlog issues now live as the next granular sync layer",
		"#70",
		"B-064: Evaluate portfolio assistant scope",
		"`priority:p2`, `type:research`, `area:backend`, `area:privacy`, `phase:8-post-launch`, `agent-standard`",
		"#71",
		"B-065: Add portfolio assistant prototype",
		"`priority:p2`, `type:feature`, `area:backend`, `area:frontend`, `area:privacy`, `phase:8-post-launch`, `agent-standard`",
		"#72",
		"B-066: Add richer public status or metadata page",
		"`priority:p2`, `type:feature`, `area:backend`, `area:frontend`, `phase:8-post-launch`, `agent-standard`",
		"#73",
		"B-067: Add additional notes and postmortems",
		"`priority:p2`, `type:content`, `area:content`, `phase:8-post-launch`, `agent-standard`",
		"#74",
		"B-068: Evaluate API hosting migration",
		"`priority:p2`, `type:research`, `area:infra`, `area:backend`, `phase:8-post-launch`, `agent-standard`",
		"Phase 8 issue sync status: complete",
		"GitHub issue-sync evidence",
		"launch-readiness evidence",
		"post-launch",
		"feature approval",
		"authorization to build the assistant before",
		"#70 has B-063 launch evidence, HumanKaylee approval, and an approved outcome",
		"HK_VERIFY_GITHUB_LIVE=1 node --test scripts/github-live-issue-sync.test.mjs",
		"Granular live GitHub issue verification",
		"issues #7 through #74",
		"Completed granular",
		"Parent epics #3 and #5 stay",
		"open while any child blocker remains open",
		"open or closed as execution advances",
		"must remain open until their external decision or evidence gate is satisfied",
		"## Deployment Sync Notes",
		"Deployment IDs, URLs, and smoke-check evidence belong in",
		"`runbooks/LAUNCH_EVIDENCE.md`, not in issue comments that might expose",
		"Required secret names if CI later deploys directly:",
		"`CLOUDFLARE_API_TOKEN`",
		"`CLOUDFLARE_ACCOUNT_ID`",
		"`FLY_API_TOKEN`",
		"`RAILWAY_TOKEN`",
		"Provider-neutral deployment and rollback guardrails are maintained in",
		"`runbooks/DEPLOYMENT.md`.",
		"Provider-specific commands, migration procedures, and rollback steps stay deferred until provider/domain decisions and required external evidence exist.",
		"Future B-068 work must re-check official provider docs before any recommendation",
		"must not choose a provider",
		"perform DNS cutover",
		"run migration commands",
		"configure env/secrets",
		"write rollback steps before",
		"B-058/B-063 evidence and HumanKaylee approval.",
	]) {
		expectContains(githubSync, required);
	}

	expectContains(
		changelog,
		"Hardened GitHub deployment sync notes and blocked-candidate body contracts",
		"deployment sync and blocked content changelog entry",
	);

	for (const staleCurrentLabel of [
		"### Current auth snapshot",
		"## Current live issue bridge",
		"current launch host evidence",
		"Exact provider commands and rollback steps are maintained in",
		"Latest Project recovery snapshot",
		"Current token scopes:",
		"Current field and item checks also succeed:",
	]) {
		assert.ok(
			!githubSync.includes(staleCurrentLabel),
			`GitHub sync should avoid stale current-state label: ${staleCurrentLabel}`,
		);
	}

	for (const required of [
		"Deferred until B-063 launch completion.",
		"Do not approve implementation before B-063 is closed and reviewed and HumanKaylee approves the B-064 decision.",
		"Blocked until B-064 has a HumanKaylee-approved build recommendation.",
		"Do not build the assistant before #70 has B-063 launch evidence, HumanKaylee approval, and an approved outcome of build.",
		"fetchAllIssues",
		"--paginate",
		"mustRemainOpenIssueNumbers",
		"parentEpicIssueNumbers",
		"...parentEpicIssueNumbers",
		"for (const parentEpicNumber of parentEpicIssueNumbers)",
		"missing live parent epic",
		"to stay open while child blockers remain open",
		"fetchProjectItems",
		"projectItemRequiredIssueNumbers",
		"missing live Project #1 item",
		"projectItemRequiredPullRequestNumbers",
		"fetchPullRequestProjectItems",
		"missing live Project #1 item for PR",
		'item["agent Size"]',
		"expected Project #1 item for",
		"to have populated",
	]) {
		expectContains(githubLiveIssueSync, required);
	}

	assert.ok(
		!githubLiveIssueSync.includes('"--limit",\n\t\t\t"100"'),
		"live issue verifier should not rely on a 100-issue result ceiling",
	);
});
